name: Rust

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Lint
        run: cargo clippy --lib -- -D warnings

  lint-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1
      - uses: jetli/wasm-pack-action@v0.3.0

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Lint (wasm32)
        run: cargo clippy --target wasm32-unknown-unknown --lib -- -D warnings

  desktop:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - name: Test
        run: cargo test -- --nocapture
        env:
          RUST_BACKTRACE: 1

  # web:
  #   runs-on: ubuntu-latest
  #   needs: lint-wasm

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable

  #     - uses: Swatinem/rust-cache@v1
  #     - uses: jetli/wasm-pack-action@v0.3.0

  #     - name: Add wasm32 target
  #       run: rustup target add wasm32-unknown-unknown

  #     - name: Test
  #       run: wasm-pack test --headless --chrome
